### ISSUE TITLE
README change

### ISSUE THREAD

**Issue by jonathanpeterwu** [rkorzeniec/simple_encryptable#11]
The readme example mentions using this syntax

```
    attr_encryptor :secret_attribute, :another_secret_attribute, secret: 'foo', salt: 'bar'
```

Based on the src it should be

```
  attr_encryptable  :secret_attribute, :another_secret_attribute, secret: 'foo', salt: 'bar'
```

**Comment by rkorzeniec** [comment]
Thank you @jonathanpeterwu, in the beginning I had few concepts for this gem `attr_encryptor` naming was used, yet I forgot to change the readme. Thanks again, merged with #12
